version: '3.9'
services:
  # This service will run our project in Production mode
  openweathermap:
    build: .
    ports:
      - "59178:59178" # Final end point
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
  # Database service
  db:
    image: postgres:bullseye
    restart: always
    environment:
      # In a production environment this parameters must be handled
      # differently. Never place text plain password!
      - POSTGRES_DB=openweathermap
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  # End point for basic database management
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

